-- ============================================================================
-- JASHOOTS — 0003: Operations core
-- Lead-driven pipeline. ENQUIRY != BOOKING.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- admin_users — Studio staff (crew auth.users)
-- ---------------------------------------------------------------------------
create table if not exists public.admin_users (
  id            uuid primary key references auth.users (id) on delete cascade,
  role          public.user_role not null default 'editor',
  display_name  text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- clients — customer records (WhatsApp-identified first; auth_user_id links
-- the portal account once booking is confirmed)
-- ---------------------------------------------------------------------------
create table if not exists public.clients (
  id            uuid primary key default gen_random_uuid(),
  auth_user_id  uuid references auth.users (id) on delete set null,
  name          text not null,
  phone         text,
  email         text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create unique index if not exists idx_clients_auth on public.clients (auth_user_id)
  where auth_user_id is not null;
create unique index if not exists idx_clients_email on public.clients (lower(email))
  where email is not null;
create index if not exists idx_clients_phone on public.clients (phone)
  where phone is not null;

-- ---------------------------------------------------------------------------
-- leads — JS-XXXX enquiry records with source attribution + abandonment (A8)
-- ---------------------------------------------------------------------------
create table if not exists public.leads (
  id                  uuid primary key default gen_random_uuid(),
  ref                 text not null unique, -- JS-1048, generated by trigger
  client_id           uuid references public.clients (id) on delete set null,
  service_id          uuid references public.services (id) on delete set null,
  package_id          uuid references public.packages (id) on delete set null,

  -- attribution (source_page / source_content = ai.conversion_event language)
  source_page         text,
  source_content      text,
  utm                 jsonb not null default '{}'::jsonb,

  -- enquiry form fields
  name                text not null,
  phone               text not null,
  email               text,
  event_type          text,          -- "What are you shooting?"
  event_date          date,
  event_location      text,
  preferred_time      text,
  requirements        text,
  budget_interest     text,          -- OPTIONAL
  extra_details       text,          -- OPTIONAL / additional details

  stage               public.lead_stage not null default 'enquiry',
  whatsapp_opened_at  timestamptz,   -- abandonment tracking
  abandoned_at        timestamptz,
  resolved_reason     text,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index if not exists idx_leads_stage       on public.leads (stage, created_at desc);
create index if not exists idx_leads_created     on public.leads (created_at desc);
create index if not exists idx_leads_client      on public.leads (client_id);
create index if not exists idx_leads_source      on public.leads (source_page, source_content);
create index if not exists idx_leads_date        on public.leads (event_date);

-- ---------------------------------------------------------------------------
-- quotes
-- ---------------------------------------------------------------------------
create table if not exists public.quotes (
  id            uuid primary key default gen_random_uuid(),
  lead_id       uuid not null references public.leads (id) on delete cascade,
  package_id    uuid references public.packages (id) on delete set null,
  amount        numeric(12, 2),
  currency      text not null default 'INR',
  status        public.quote_status not null default 'draft',
  sent_at       timestamptz,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_quotes_lead on public.quotes (lead_id);
create index if not exists idx_quotes_status on public.quotes (status);

-- ---------------------------------------------------------------------------
-- bookings — explicit booking state machine
-- ---------------------------------------------------------------------------
create table if not exists public.bookings (
  id              uuid primary key default gen_random_uuid(),
  quote_id        uuid references public.quotes (id) on delete set null,
  lead_id         uuid references public.leads (id) on delete set null,
  client_id       uuid references public.clients (id) on delete set null,
  booking_date    date,
  location        text,
  advance_amount  numeric(12, 2),
  state           public.booking_state not null default 'confirmed',
  confirmed_by    uuid references public.admin_users (id) on delete set null,
  confirmed_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_bookings_date on public.bookings (booking_date);
create index if not exists idx_bookings_state on public.bookings (state);
create index if not exists idx_bookings_client on public.bookings (client_id);

-- ---------------------------------------------------------------------------
-- projects
-- ---------------------------------------------------------------------------
create table if not exists public.projects (
  id            uuid primary key default gen_random_uuid(),
  booking_id    uuid not null unique references public.bookings (id) on delete cascade,
  status        public.booking_state not null default 'confirmed',
  progress      integer not null default 0 check (progress between 0 and 100),
  shoot_date    date,
  shoot_location text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_projects_status on public.projects (status);

-- ---------------------------------------------------------------------------
-- deliverables — portal review media
-- ---------------------------------------------------------------------------
create table if not exists public.deliverables (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid not null references public.projects (id) on delete cascade,
  type            public.deliverable_type not null default 'reel',
  title           text,
  media_url       text,
  status          public.deliverable_status not null default 'pending',
  uploaded_by     uuid references public.admin_users (id) on delete set null,
  replaced_by_id  uuid references public.deliverables (id) on delete set null,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_deliverables_project on public.deliverables (project_id, status);
create index if not exists idx_deliverables_status on public.deliverables (status);

-- ---------------------------------------------------------------------------
-- approvals — client review / approve / reject(+feedback)
-- ---------------------------------------------------------------------------
create table if not exists public.approvals (
  id              uuid primary key default gen_random_uuid(),
  deliverable_id  uuid not null references public.deliverables (id) on delete cascade,
  client_id       uuid references public.clients (id) on delete set null,
  status          public.approval_status not null default 'pending',
  feedback        text,
  decided_at      timestamptz,
  created_at      timestamptz not null default now()
);

create index if not exists idx_approvals_deliverable on public.approvals (deliverable_id);
create unique index if not exists idx_approvals_one_round
  on public.approvals (deliverable_id, created_at);

-- ---------------------------------------------------------------------------
-- deliveries — A2 delivery abstraction (provider-agnostic) + A6 security
-- ---------------------------------------------------------------------------
create table if not exists public.deliveries (
  id              uuid primary key default gen_random_uuid(),
  project_id      uuid not null references public.projects (id) on delete cascade,
  provider        public.delivery_provider not null default 'other',
  external_url    text,
  expires_at      timestamptz,
  delivery_status public.delivery_status not null default 'pending',
  published_at    timestamptz,
  access_notes    text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_deliveries_project on public.deliveries (project_id);

-- ---------------------------------------------------------------------------
-- payments — Razorpay deposits
-- ---------------------------------------------------------------------------
create table if not exists public.payments (
  id            uuid primary key default gen_random_uuid(),
  booking_id    uuid references public.bookings (id) on delete set null,
  lead_id       uuid references public.leads (id) on delete set null,
  amount        numeric(12, 2) not null,
  currency      text not null default 'INR',
  method        public.payment_method,
  status        public.payment_status not null default 'pending',
  provider_ref  text,
  paid_at       timestamptz,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_payments_booking on public.payments (booking_id);
create index if not exists idx_payments_status on public.payments (status);

-- ---------------------------------------------------------------------------
-- notifications
-- ---------------------------------------------------------------------------
create table if not exists public.notifications (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid references public.projects (id) on delete cascade,
  booking_id    uuid references public.bookings (id) on delete cascade,
  channel       public.notification_channel not null default 'whatsapp',
  event         text,
  recipient     text,
  subject       text,
  body          text,
  status        text not null default 'pending',
  sent_at       timestamptz,
  created_at    timestamptz not null default now()
);

create index if not exists idx_notifications_created on public.notifications (created_at desc);
create index if not exists idx_notifications_project on public.notifications (project_id);

-- ---------------------------------------------------------------------------
-- conversion_events — global conversion tracking (A8); insert only via
-- SECURITY DEFINER RPC public.log_conversion_event()
-- ---------------------------------------------------------------------------
create table if not exists public.conversion_events (
  id            bigint generated always as identity primary key,
  lead_id       uuid references public.leads (id) on delete set null,
  session_id    text,
  event_name    public.conversion_event_name not null,
  page          text,
  context       jsonb not null default '{}'::jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists idx_conv_events_time on public.conversion_events (created_at);
create index if not exists idx_conv_events_name on public.conversion_events (event_name, created_at desc);
create index if not exists idx_conv_events_lead on public.conversion_events (lead_id);
create index if not exists idx_conv_events_session on public.conversion_events (session_id);

-- ---------------------------------------------------------------------------
-- audit_logs — audit trail (price, quote, booking, payment, approval,
-- media replacement, delivery publication, lead stage)
-- ---------------------------------------------------------------------------
create table if not exists public.audit_logs (
  id            bigint generated always as identity primary key,
  actor_type    text not null default 'system',
  actor_id      uuid,
  action        text not null,
  entity_type   text not null,
  entity_id     text,
  before        jsonb,
  after         jsonb,
  created_at    timestamptz not null default now()
);

create index if not exists idx_audit_entity on public.audit_logs (entity_type, entity_id);
create index if not exists idx_audit_created on public.audit_logs (created_at desc);
create index if not exists idx_audit_actor on public.audit_logs (actor_id);